@include('vue.scripts.general')
@include('vue.scripts.ajax')
@include('vue.scripts.filters')
@include('vue.scripts.directives')

@include('vue.components.button_group')
@include('vue.components.datepicker')
@include('vue.components.delete')
@include('vue.components.icheck')
@include('vue.components.modal')
@include('vue.components.select2')
@include('vue.components.single_tag')
@include('vue.components.vue_form')
@include('vue.components.vue_table')

@include('vue.components.vue_table.edit_row')
@include('vue.components.vue_table.show_row')
@include('vue.components.vue_table.table_pager')
@include('vue.components.vue_table.table_searcher')
@include('vue.components.vue_table.table_page_sizer')

@include('vue.mixins.table_paging')
@include('vue.mixins.table_searching')
@include('vue.mixins.table_sorting')